.TH ARCH-SCRIPTS 1 "2026-05-28" "v0.6.8" "Arch Scripts Manual"
.SH NAME
arch-scripts \- a simple CLI tool to update, configure, install, and do more stuff on Arch Linux
.SH SYNOPSIS
\fBarch-scripts\fR \fB\-v\fR|\fB\-\-version\fR
.br
\fBarch-scripts\fR \fB\-h\fR|\fB\-\-help\fR
.SH DESCRIPTION
\fBarch-scripts\fR is a simple CLI tool, built for arch. It is to easily configure, install, update, and do more stuff on arch linux.
.PP
It is mainly made in python, so python is necessary to run this software.
.SH OPTIONS
.TP
\fB\-\-help\fR, \fB\-h\fR
Shows the help message and exits
.TP
\fB\-\-version\fR, \fB\-v\fR
Shows the current software version
.SH SUBCOMMANDS
.TP
\fBinstall\fR
Installs a pack of packages.
.TP
\fBupdate\fR
Updates the system using pacman, and your AUR helper.
.TP
\fBconfig\fR
Configures arch linux. Arguments:
.RS
.TP
\fB\-\-dns\fR {\fBquad9\fR, \fBcloudflare\fR, \fBadguard\fR, \fBgoogle\fR}
Changes the DNS on systemd-resolved.
.TP
\fB\-\-change\-hostname\fR
Changes the system hostname.
.TP
\fB\-\-change\-shell\fR
Changes the default shell for the current user.
.RE
.SH AUTHORS
Written by Andrew P. <itspixelatd@proton.me>
