.TH ARCH-SCRIPTS 1 "May 29, 2026" "v1.3.0" "Arch-Scripts Manual"
.SH NAME
arch-scripts \- a simple cli tool, to update, configure, and install things on arch linux easily.
.SH SYNOPSIS
.B arch-scripts
.I COMMAND
\fR[\fIoptions\fR]
.SH COMMANDS (SUB-COMMANDS)
.TP
.B install
Installs packages in packs, for your needs
.TP
.B config
Configures settings on arch linux.
.TP
.B update
Updates AUR, and pacman packages.
.SH CONFIG OPTIONS
.TP
.B --change-shell
Changes shell for the current user
.TP
.B --change-hostname
Changes the system hostname
.TP
.BI --dns " {quad9, cloudflare, google, adguard}"
Changes the systemd-resolved DNS to the one of the ones above
.TP
.B --mirror-rank
Ranks your pacman mirrors from /etc/pacman.d/mirrorlist
.TP
.B --swapiness
Changes your memory swapiness
.TP
.B --journal-limit
Limits your systemd journald logs to 200MB max
.PP
For install options, run
.B arch-scripts install -h, --help
.SH AUTHOR
Andrew P. <itspixelatd@proton.me>